title:              Renan Coelho
email:              coelhorzd@gmail.com
description:        UX Design portfolio
author:             Renan Coelho
baseurl:
url:

# Social Profiles
twitter_username:
github_username: 
instagram_username: coelho_rr
linkedin_username:  coelho-renan

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-161042866-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
