title:              Renan R Coelho
email:              coelhorzd@gmail.com
description:        UX Design portfolio
author:             Renan R Coelho
baseurl:
url:
collections:
  physical:
    output: true
    permalink: /physical/:name

# Social Profiles
twitter_username:
github_username: coelhorzd
facebook_username:
linkedin_username:  coelho-renan

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-161042866-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
